=== Ivanjois/FSDAM/1 año/LM SERGIO/1 evaluacion/Tema3II/coche.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Ivan Poyda-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="oferta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"/>

                            <xs:element name="modelo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="color" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="blanco"/>
                                                        <xs:enumeration value="gris"/>
                                                        <xs:enumeration value="champagne"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="motor">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="combustible" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="gasolina"/>
                                                        <xs:enumeration value="diesel"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="matricula" type="xs:string"/>

                            <xs:element name="kilometros" type="xs:integer"/>

                            <xs:element name="precio_inicial" type="xs:decimal"/>
                            <xs:element name="precio_oferta" type="xs:decimal"/>

                            <xs:element name="extra" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="valor" type="xs:decimal" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="foto" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="imagen" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Ivanjois/FSDAM/1 año/LM SERGIO/1 evaluacion/Tema3II/coches.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<oferta>
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="coche.xsd">
  <vehiculo>
    <marca>Marca:  Ford</marca>
    <modelo color="blanco">Modelo: Focus RS 2017</modelo>
    <motor combustible="gasolina">Motor: duratorc 14  </motor>
    <matricula>Matricula: 1234AAA</matricula>
    <kilometros>Kilometros:  12500 </kilometros>
    <precio_inicial>El precio inicial es de 12500&#8364;</precio_inicial>
    <precio_oferta>Precio oferta 10000&#8364;</precio_oferta>
    <extra valor="250">pintura metalizada</extra>
    <extra valor="300">llantas</extra>
    <foto imagen="fordblanco"/>
   <foto imagen="fordblanco2"/>
</vehiculo>

<vehiculo>
    <marca>Marca:  MERCEDES-BENZ</marca>
	<modelo color="champagne">Modelo:  Clase CLA</modelo>
	<motor combustible="diesel">CLA 200 d, 136cv</motor>
    <matricula>Matricula: 0000BBB</matricula>
	<kilometros>Kilometros:  3500 </kilometros>
	<precio_inicial>El precio inicial es de 22500&#8364;</precio_inicial>
	<precio_oferta>Precio oferta 20000&#8364;</precio_oferta>	
    <extra valor="150">Navegador Garmin MAP PILOT</extra>
    <extra valor="350">Techo corredizo panoramico</extra>	
    <foto imagen="mercedes"/>
    <foto imagen="mercedes2"/>
</vehiculo>

<vehiculo>
    <marca>Marca:  Audi</marca>
	<modelo color="blanco">Modelo:  A5 S line coupe</modelo>
	<motor combustible="gasolina">2.0 TDI 190CV</motor>
    <matricula>Matricula: 9999KKK</matricula>
	<kilometros>Kilometros:  100 </kilometros>
	<precio_inicial>El precio inicial es de 36500&#8364;</precio_inicial>
	<precio_oferta>Precio oferta 35000&#8364;</precio_oferta>	
    <extra valor="170">Camara de marcha atras</extra>
    <extra valor="180">Tapiceria en cuero Milano</extra>	
    <foto imagen="audiA5"/>
    <foto imagen="audiA52"/>
</vehiculo>

  <vehiculo>
    <marca>Maraca: Opel</marca>
    <modelo color="gris">Modelo: Astra</modelo>
    <motor combustible="diesel">Motor: Turbo 2.0 </motor>
    <matricula>Matricula: 1235AAA</matricula>
    <kilometros>Kilometros: 125000</kilometros>
    <precio_inicial>El precio inicial es de 10000&#8364;</precio_inicial>
    <precio_oferta>Precio oferta 9000&#8364;</precio_oferta>
    <extra valor="250">pintura metalizada</extra>
    <extra valor="200">spoiler trasero</extra>
    <extra valor="500">climatizador</extra>
    <foto imagen="opel"/>
     <foto imagen="opel2"/>
</vehiculo>


 
</oferta>
